name: LoveNote
options:
  bundleIdPrefix: com.vibegang
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  LoveNote:
    type: application
    platform: iOS
    sources:
      - LoveNote
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibegang.lovenote
        SDKROOT: iphoneos
